### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by sasholy** [wzqs/endpoints_explore#12]
Hi? sorry but what means - base_url normal_paths_dict , sensitive_files_dict
are there examples, thx

**Comment by wzqs** [comment]
Consider reviewing the readme. 'base_url' is the URL for testing. 'normal_paths_dict' is a file with normal test URL paths, collected and de-duplicated via methods like web crawling. 'sensitive_files_dict' contains sensitive file paths (e.g., /actuator/env, available on GitHub). Inaccessible interfaces can also be included. The associated path for 'normal_paths_dict' is /.
